Leave/Controllers/Leave_TypeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Leave.Contracts;
using Leave.Controllers;
using AutoMapper;
using Leave.Data;
using Leave.Models;

namespace Leave.Controllers
{
    public class Leave_TypeController : Controller
    {
        private readonly ILeaveTyperepository _repo;
        private readonly IMapper _Mapper;


        public Leave_TypeController(ILeaveTyperepository repo, IMapper Mapper)
        {
            _repo = repo;
            _Mapper = Mapper;
                
        }

        // GET: Leave_TypeController
        public ActionResult Index()
        {
            var leave_typs = _repo.FindAll().ToList();
            var model=_Mapper.Map<List<Leave_type>,List<Leave_type_view_model> >(leave_typs);
            return View(model);
        }

        // GET: Leave_TypeController/Details/5
        public ActionResult Details(int id)     //check actually exist and then show
        {
            if(!_repo.isExists(id))
            {
                return NotFound();
            }
            var Leave_typs = _repo.FindById(id);
            var model = _Mapper.Map<Leave_type_view_model>(Leave_typs);
            return View(model);
        }

        // GET: Leave_TypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Leave_TypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]                          //works after entering the details
        public ActionResult Create(Leave_type_view_model model)
        {
            try
            {
                // checking validation what are criterias?
                if(!ModelState.IsValid)
                {
                    return View(model);
                }

                var leave_typs = _Mapper.Map<Leave_type>(model);            // maping model to leave_type
                leave_typs.Date_created=DateTime.Now;                       // settiing Date_created automatically

                var isSuccess=_repo.Create(leave_typs);                     //checking added or not
                if(!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...:( ");     //showing error Format:("key_value","message")
                    return View(model);             //returnig the entered data
                }

                return RedirectToAction(nameof(Index));             // iff all thing gone right go to index (shoe Leave_types)
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...:( ");
                return View();
            }
        }

        // GET: Leave_TypeController/Edit/5
        public ActionResult Edit(int id)
        {
            if(!_repo.isExists(id))
            {
                return NotFound();

            }
            var leave_typs = _repo.FindById(id);
            var model = _Mapper.Map<Leave_type_view_model>(leave_typs);
            return View(model);
        }

        // POST: Leave_TypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Leave_type_view_model model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var leave_typs = _Mapper.Map<Leave_type>(model);
                var isSuccess = _repo.Update(leave_typs);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...:( ");     //showing error Format:("key_value","message")
                    return View(model);             //returnig the entered data
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...:( ");     //showing error Format:("key_value","message")
                return View(model);
                
            }
        }

        // GET: Leave_TypeController/Delete/5
        public ActionResult Delete(int id)                      //for conformation message
        {
            if (!_repo.isExists(id))
            {
                return NotFound();
            }
            else
            {
                var leave_typs = _repo.FindById(id);
                var model = _Mapper.Map<Leave_type_view_model>(leave_typs);
                return View(model);
            }
        }

        // POST: Leave_TypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Leave_type_view_model model)
        {
            try
            {
                var leave_typs = _repo.FindById(id);
                if(leave_typs== null)
                {
                    return NoContent();
                }
                var isSucess = _repo.Delete(leave_typs);
                if(!isSucess)
                {
                    ModelState.AddModelError("","Something went wrong to delete....");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong to delete....");
                return View(model);
            }
        }
    }
}

Leave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leave</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/fontawesome.min.css" integrity="sha384-zIaWifL2YFF1qaDiAo0JFgsmasocJ/rqu7LKYH8CoBEXqGbb9eO+Xi3s6fQhgFWM" crossorigin="anonymous"> *@
    @*-----Error here------*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Leave.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leave</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leave_Type" asp-action="Index">Leave type</a>
                        </li>
                            
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Leave_Type" asp-action="Index">LEAVE TYPE</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                          </ul>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @DateTime.Now.TimeOfDay   --    @DateTime.Now.Date - Leave - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>